apiVersion: v1
kind: ConfigMap
metadata:
  name: project1-config
  namespace: project1-cdc
data:
  KAFKA_BOOTSTRAP: "kafka:9092"
  KAFKA_TOPICS: "dbserver_docker.public.orders,dbserver_docker.public.users,dbserver_docker.public.payments"
  KAFKA_STARTING_OFFSETS: "earliest"
  ICEBERG_WAREHOUSE: "s3a://warehouse/iceberg"
  BRONZE_CKPT: "s3a://warehouse/checkpoints/bronze/raw_cdc"
  SILVER_CKPT: "s3a://warehouse/checkpoints/silver/merge"
  S3_ENDPOINT: "http://minio:9000"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  PROJECT_ROOT: "/app"
