name: cd pipeline

on:
  workflow_run:
    workflows: [ "ci pipeline" ]
    types: [ completed ]
    branches: [ main, dev ]

jobs:
  deploy_projects:
    name: deploy projects
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3

      - name: write release info
        run: |
          mkdir -p release_info
          echo '{"branch":"${{ github.event.workflow_run.head_branch }}","sha":"${{ github.event.workflow_run.head_sha }}","time":"${{ github.event.workflow_run.updated_at }}","scope":["project_1","project_2","project_3"]}' > release_info/release_info.json

      - name: upload release info
        uses: actions/upload-artifact@v3
        with:
          name: release_info
          path: release_info/release_info.json
